version: "3.7"
services:
  # nginx
  srv_nginx:
    container_name: local_srv_nginx
    build:
      context: configs
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
    links:
      - srv_php
    environment:
      - VIRTUAL_HOST=${WEB_VIRTUAL_HOST}
    volumes:
      - ${PROJECT_PUBLIC_PATH}:/app/public
  # MySQL
  srv_mysql:
    container_name: local_srv_mysql
    build:
      context: configs
      dockerfile: mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  # phpMyAdmin
  srv_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: local_srv_phpmyadmin
    links:
      - srv_mysql
    environment:
      PMA_HOST: srv_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  # PHP-FPM
  srv_php:
    container_name: local_srv_php
    environment:
      UPLOAD_MAX_FILESIZE: 100M
      POST_MAX_SIZE: 1000M
      MEMORY_LIMIT: 2048M
      DATE_TIMEZONE: Europe/Bucharest
    build:
      context: configs
      dockerfile: php/Dockerfile
    volumes:
      - /tmp:/tmp
      - ${PROJECT_PATH}:/app
      - /profile:/etc/profile.d
  # PHPCS
  srv_phpcs:
    container_name: local_srv_phpcs
    build:
      context: configs
      dockerfile: phpcs/Dockerfile
    tty: true
    volumes:
      - /tmp:/tmp
