version: "3.7"
services:
  # nginx
  srv_nginx:
    container_name: local_srv_nginx
    build:
      context: configs
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
    links:
      - srv_php
    environment:
      - VIRTUAL_HOST=${WEB_VIRTUAL_HOST}
    volumes:
      - ${PROJECT_PUBLIC_PATH}:/app/public
  # MySQL
  srv_mysql:
    container_name: local_srv_mysql
    build:
      context: configs
      dockerfile: mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  # PHP-FPM
  srv_php:
    container_name: local_srv_php
    build:
      context: configs
      dockerfile: php/Dockerfile
    volumes:
      - /tmp:/tmp
      - ${PROJECT_PATH}:/app
  # PHPCS
  srv_phpcs:
    container_name: local_srv_phpcs
    build:
      context: configs
      dockerfile: phpcs/Dockerfile
    tty: true
    volumes:
      - /tmp:/tmp
